In [20]:
import gym
import numpy as np
from tensorboardX import SummaryWriter
import torch
from torch import nn
from torch.optim import Adam

OBSERVATION_SIZE = env.observation_space.shape[0]
NUM_ACTIONS = env.action_space.n
HIDDEN_SIZE = 128
BATCH_SIZE = 16
PERCENTILE = 70

network = nn.Sequential(
    nn.Linear(in_features=OBSERVATION_SIZE, out_features=HIDDEN_SIZE),
    nn.ReLU(),
    nn.Linear(in_features=HIDDEN_SIZE, out_features=NUM_ACTIONS),
)

sm = nn.Softmax(dim=1)

env = gym.make('CartPole-v0')
obs = env.reset()
obs_v = torch.FloatTensor([obs])
act_probabilities_v = sm(network(input=obs_v))
act_probabilities = act_probabilities_v.data.numpy()[0]

print(obs_v)
print(network(obs_v))
print(act_probabilities_v)
print(act_probabilities)

tensor([[ 0.0357,  0.0454,  0.0149, -0.0422]])
tensor([[-0.1017,  0.0787]], grad_fn=<AddmmBackward>)
tensor([[0.4550, 0.5450]], grad_fn=<SoftmaxBackward>)
[0.4550201  0.54497993]
